site_name: OpenMPF
theme: readthedocs
copyright: OpenMPF

markdown_extensions:
- toc

pages:
- Home: index.md
- Build Guide: Build-Environment-Setup-Guide.md
- Install Guide: MPF-Installation.md
- User Guide: MPF-User-Guide.md
- Admin Guide: MPF-Admin-Manual.md
- Component Documentation:
    - Component Overview: API-Overview.md
    - C++ Component API: CPP-Component-API.md
    - Packaging and Registering a Component: Packaging-and-Registering-a-Component.md
- REST API Documentiaton: REST-API.md
